(()=>{
const KEY='thoughts_assistant_v1',LEGACY=['thoughts_app_v2','thoughts','ideas','mindItems','thoughtsAppItems'];
const L={
he:{home:'דף הבית',kicker:'מקום אחד לכל מה שלא בא לך לשכוח',title:'מה עובר לך\\nבראש?',subtitle:'לכתוב, לדבר, לתזמן — ולתת למחשבות החשובות לחזור בזמן הנכון.',placeholder:'כתוב מחשבה, משימה, אירוע או אדם שתרצה לזכור...',inputHint:'אפשר גם פשוט לדבר',itemType:'סוג פריט',typeThought:'מחשבה / משימה',typeEvent:'אירוע',typeFriend:'חבר / אדם',schedule:'תזמון',add:'הוספת פריט',activeStat:'פריטים פעילים',scheduledStat:'מתוזמנים',dueStat:'מחכים עכשיו',yourThoughts:'הפריטים שלך',yourThoughtsSub:'מה שחשוב עכשיו נשאר קרוב.',active:'פעילים',archived:'ארכיון',all:'הכול',emptyTitle:'הכול שקט כאן',empty:'הפריט הבא שלך יכול להתחיל למעלה.',local:'הפריטים נשמרים מקומית במכשיר הזה.',scheduleTitle:'מתי להזכיר לך?',date:'תאריך',time:'שעה',repeat:'חזרה',none:'ללא חזרה',daily:'פעם ביום',threeDays:'פעם בשלושה ימים',weekly:'פעם בשבוע',biweekly:'פעם בשבועיים',monthly:'פעם בחודש',bimonthly:'פעם בחודשיים',random:'להפתיע אותי מדי פעם',randomHelp:'הפריט יחזור במועד אקראי לפי התדירות שתבחר.',frequency:'באיזו תדירות?',clear:'ללא תזמון',save:'שמירה',editTitle:'עריכת פריט',changeSchedule:'שינוי תזמון',saveChanges:'שמירת שינויים',deleteTitle:'למחוק את הפריט?',deleteHelp:'המחיקה סופית. אם אולי תרצה לחזור אליו, אפשר להעביר אותו לארכיון.',cancel:'ביטול',delete:'מחיקה',edit:'עריכה',archive:'ארכיון',restore:'החזרה',done:'בוצע',nextOccurrence:'הבא',scheduled:'מתוזמן',repeats:'חוזר',due:'הגיע הזמן',randomChip:'אקראי',voiceNote:'פריט קולי',added:'הפריט נוסף',updated:'הפריט עודכן',deleted:'הפריט נמחק',archivedToast:'הועבר לארכיון',restoredToast:'הוחזר מהארכיון',next:'המועד הבא נקבע אוטומטית',writeFirst:'אפשר לכתוב או להקליט משהו קודם',listening:'מקשיב… דבר עכשיו',recording:'מקליט… לחיצה נוספת תעצור',voiceReady:'ההקלטה מוכנה להוספה',voiceDenied:'אין הרשאה למיקרופון. יש לאפשר גישה למיקרופון בהגדרות האתר.',voiceNoSpeech:'לא הצלחתי לזהות דיבור. אפשר לנסות שוב.',voiceError:'ההקלטה לא הצליחה. אפשר לנסות שוב.'},
en:{home:'Home',kicker:'One place for what you do not want to forget',title:'What is on\\nyour mind?',subtitle:'Write it, say it, schedule it — and let important things return at the right time.',placeholder:'Write a thought, task, event, or person you want to remember...',inputHint:'You can also just speak',itemType:'Item type',typeThought:'Thought / task',typeEvent:'Event',typeFriend:'Friend / person',schedule:'Schedule',add:'Add item',activeStat:'Active items',scheduledStat:'Scheduled',dueStat:'Due now',yourThoughts:'Your items',yourThoughtsSub:'What matters now stays close.',active:'Active',archived:'Archive',all:'All',emptyTitle:'All quiet here',empty:'Your next item can start above.',local:'Items are stored locally on this device.',scheduleTitle:'When should I remind you?',date:'Date',time:'Time',repeat:'Repeat',none:'No repeat',daily:'Once a day',threeDays:'Every three days',weekly:'Once a week',biweekly:'Every two weeks',monthly:'Once a month',bimonthly:'Every two months',random:'Surprise me sometimes',randomHelp:'This item will resurface randomly at the frequency you choose.',frequency:'How often?',clear:'No schedule',save:'Save',editTitle:'Edit item',changeSchedule:'Change schedule',saveChanges:'Save changes',deleteTitle:'Delete this item?',deleteHelp:'Deletion is permanent. Archive it instead if you may want it later.',cancel:'Cancel',delete:'Delete',edit:'Edit',archive:'Archive',restore:'Restore',done:'Done',nextOccurrence:'Next',scheduled:'Scheduled',repeats:'Repeats',due:'Due now',randomChip:'Random',voiceNote:'Voice item',added:'Item added',updated:'Item updated',deleted:'Item deleted',archivedToast:'Moved to archive',restoredToast:'Restored',next:'Next occurrence scheduled automatically',writeFirst:'Write or record something first',listening:'Listening… speak now',recording:'Recording… tap again to stop',voiceReady:'Recording is ready to add',voiceDenied:'Microphone permission is blocked. Allow microphone access in this site’s settings.',voiceNoSpeech:'I could not recognize speech. Try again.',voiceError:'Voice capture failed. Try again.'}
};
const $=id=>document.getElementById(id),S={items:[],filter:'active',lang:localStorage.getItem('thoughts_lang')||'he',pending:null,target:null,edit:null,del:null,pendingAudioId:null,draftAudioUrl:null};
const t=k=>L[S.lang][k]||k,save=()=>localStorage.setItem(KEY,JSON.stringify(S.items));
function normalizeItem(x,n=0){return{id:String(x.id||Date.now()+'_'+n),text:x.text||x.title||x.content||'',type:['thought','event','friend'].includes(x.type)?x.type:'thought',createdAt:x.createdAt||new Date().toISOString(),archived:!!x.archived,done:!!x.done,schedule:x.schedule||null,random:x.random||null,audioId:x.audioId||null,lastNotifiedAt:x.lastNotifiedAt||null}}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const a=JSON.parse(raw)||[];S.items=Array.isArray(a)?a.map(normalizeItem):[]}else{for(const k of LEGACY){const r=localStorage.getItem(k);if(!r)continue;const a=JSON.parse(r);if(Array.isArray(a)){S.items=a.map(normalizeItem).filter(x=>x.text||x.audioId);save();break}}}}catch{S.items=[]}}
function toast(x){const e=$('toast');e.textContent=x;e.classList.add('show');clearTimeout(toast.h);toast.h=setTimeout(()=>e.classList.remove('show'),1900)}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function lang(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==='he'?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(e=>{const v=t(e.dataset.t);e.innerHTML=v.replace('\\n','<br>')});document.querySelectorAll('[data-ph]').forEach(e=>e.placeholder=t(e.dataset.ph));$('lang').textContent=S.lang==='he'?'EN':'עברית';render();updatePending()}
function iso(s){if(!s?.date||!s?.time)return null;const d=new Date(`${s.date}T${s.time}:00`);return isNaN(d)?null:d.toISOString()}
function fmt(x){if(!x)return'';try{return new Intl.DateTimeFormat(S.lang==='he'?'he-IL':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}catch{return''}}
function rndMs(v){return({daily:86400000,'3days':259200000,weekly:604800000,biweekly:1209600000})[v]||86400000}
function nextRandom(v){const span=rndMs(v),min=Math.min(7200000,span*.15);return new Date(Date.now()+min+Math.random()*(span-min)).toISOString()}
function due(i){const a=iso(i.schedule),b=i.random?.enabled?i.random.nextAt:null;return !!((a&&new Date(a)<=new Date())||(b&&new Date(b)<=new Date()))}
function addMonths(d,n){const day=d.getDate();d=new Date(d);d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d}
function nextDate(d,r){d=new Date(d);if(r==='daily')d.setDate(d.getDate()+1);else if(r==='3days')d.setDate(d.getDate()+3);else if(r==='weekly')d.setDate(d.getDate()+7);else if(r==='biweekly')d.setDate(d.getDate()+14);else if(r==='monthly')d=addMonths(d,1);else if(r==='bimonthly')d=addMonths(d,2);return d}
function repeatText(v){return v==='3days'?t('threeDays'):t(v||'none')}
function typeText(v){return t(v==='event'?'typeEvent':v==='friend'?'typeFriend':'typeThought')}
function typeClass(v){return v==='event'?'event':v==='friend'?'friend':'type'}
function render(){
  const active=S.items.filter(i=>!i.archived);
  $('activeCount').textContent=active.length;
  $('scheduledCount').textContent=active.filter(i=>i.schedule||i.random?.enabled).length;
  $('dueCount').textContent=active.filter(due).length;
  const a=S.items.filter(i=>S.filter==='all'||(S.filter==='active'?!i.archived:i.archived)).sort((x,y)=>(due(x)?0:1)-(due(y)?0:1)||new Date(y.createdAt)-new Date(x.createdAt));
  $('list').innerHTML='';$('empty').classList.toggle('hidden',!!a.length);
  a.forEach(i=>{
    const c=document.createElement('article'),si=iso(i.schedule),chips=[];
    c.className='card'+(due(i)?' due':si?' scheduled':'');c.dataset.id=i.id;
    chips.push(`<span class="chip ${typeClass(i.type)}">${esc(typeText(i.type))}</span>`);
    if(due(i))chips.push(`<span class="chip due">${esc(t('due'))}</span>`);
    if(si)chips.push(`<span class="chip">${esc(t('scheduled'))}: ${esc(fmt(si))}</span>`);
    if(i.schedule?.repeat&&i.schedule.repeat!=='none')chips.push(`<span class="chip repeat">${esc(t('repeats'))}: ${esc(repeatText(i.schedule.repeat))}</span>`);
    if(i.random?.enabled)chips.push(`<span class="chip random">${esc(t('randomChip'))}: ${esc(repeatText(i.random.frequency))}</span>`);
    if(i.done)chips.push(`<span class="chip done">${esc(t('done'))}</span>`);
    const recurring=!!(i.schedule?.repeat&&i.schedule.repeat!=='none');
    c.innerHTML=`<div class="cardTop"><span class="statusMark"></span><div style="flex:1"><div class="thought">${esc(i.text||t('voiceNote'))}</div><div class="chips">${chips.join('')}</div><div class="audioCard ${i.audioId?'':'hidden'}" data-audio="${esc(i.audioId||'')}"></div></div></div><div class="cardActions"><button class="small edit">${esc(t('edit'))}</button><button class="small schedule">${esc(t('schedule'))}</button><button class="small complete">${esc(recurring?t('nextOccurrence'):t('done'))}</button><button class="small archive">${esc(i.archived?t('restore'):t('archive'))}</button><button class="small delete">${esc(t('delete'))}</button></div><div class="meta">${esc(fmt(i.createdAt))}</div>`;
    $('list').appendChild(c)
  });
  hydrateAudio()
}
function updatePending(){const e=$('pending');if(!S.pending?.schedule&&!S.pending?.random){e.classList.remove('show');return}const p=[];if(S.pending.schedule)p.push(fmt(iso(S.pending.schedule)));if(S.pending.schedule?.repeat&&S.pending.schedule.repeat!=='none')p.push(t('repeats')+' · '+repeatText(S.pending.schedule.repeat));if(S.pending.random?.enabled)p.push(t('randomChip')+' · '+repeatText(S.pending.random.frequency));$('pendingText').textContent=p.join(' · ');e.classList.add('show')}
function openSchedule(id=null){S.target=id;const i=id?S.items.find(x=>x.id===id):null,v=i||S.pending||{},s=v.schedule||{},r=v.random||{},now=new Date(),p=n=>String(n).padStart(2,'0');$('date').value=s.date||`${now.getFullYear()}-${p(now.getMonth()+1)}-${p(now.getDate())}`;$('time').value=s.time||`${p(Math.min(23,now.getHours()+1))}:00`;$('repeat').value=s.repeat||'none';$('randomOn').checked=!!r.enabled;$('frequency').value=r.frequency||'daily';$('randomWrap').classList.toggle('hidden',!r.enabled);$('scheduleDlg').showModal()}
function scheduleValue(){const schedule=$('date').value&&$('time').value?{date:$('date').value,time:$('time').value,repeat:$('repeat').value}:null;const random=$('randomOn').checked?{enabled:true,frequency:$('frequency').value,nextAt:nextRandom($('frequency').value)}:null;return{schedule,random}}
function advance(i){const r=i.schedule?.repeat,si=iso(i.schedule);if(si&&r&&r!=='none'){let n=nextDate(new Date(si),r);while(n<=new Date())n=nextDate(n,r);const p=x=>String(x).padStart(2,'0');i.schedule.date=`${n.getFullYear()}-${p(n.getMonth()+1)}-${p(n.getDate())}`;i.schedule.time=`${p(n.getHours())}:${p(n.getMinutes())}`;i.done=false;i.lastNotifiedAt=null;if(i.random?.enabled)i.random.nextAt=nextRandom(i.random.frequency);toast(t('next'))}else i.done=true}
const DB='thoughts_voice_db';
function dbOpen(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>q.result.createObjectStore('audio');q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function audioPut(id,blob){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction('audio','readwrite');tx.objectStore('audio').put(blob,id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function audioGet(id){if(!id)return null;try{const db=await dbOpen();return await new Promise((res,rej)=>{const q=db.transaction('audio').objectStore('audio').get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}catch{return null}}
async function audioDelete(id){if(!id)return;try{const db=await dbOpen();db.transaction('audio','readwrite').objectStore('audio').delete(id)}catch{}}
async function hydrateAudio(){document.querySelectorAll('[data-audio]').forEach(async el=>{if(el.dataset.ready||!el.dataset.audio)return;const b=await audioGet(el.dataset.audio);if(!b)return;const url=URL.createObjectURL(b);el.innerHTML=`<audio controls preload="metadata" src="${url}"></audio>`;el.dataset.ready='1'})}
function clearDraftAudio(){if(S.draftAudioUrl)URL.revokeObjectURL(S.draftAudioUrl);if(S.pendingAudioId)audioDelete(S.pendingAudioId);S.pendingAudioId=null;S.draftAudioUrl=null;$('audioDraft').classList.remove('show');$('draftAudio').removeAttribute('src')}
let recognition=null,listening=false,recorder=null,stream=null,chunks=[],speechBase='';
function voiceUi(on,label){listening=on;$('voice').classList.toggle('listening',on);$('voiceState').classList.toggle('show',on);$('voiceLabel').textContent=label||t('listening')}
async function micPermission(){if(!navigator.mediaDevices?.getUserMedia)return null;const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(x=>x.stop());return true}
async function startRecorder(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=async()=>{stream?.getTracks().forEach(x=>x.stop());stream=null;const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});const id='a_'+Date.now()+'_'+Math.random().toString(36).slice(2);await audioPut(id,blob);S.pendingAudioId=id;if(S.draftAudioUrl)URL.revokeObjectURL(S.draftAudioUrl);S.draftAudioUrl=URL.createObjectURL(blob);$('draftAudio').src=S.draftAudioUrl;$('audioDraft').classList.add('show');voiceUi(false);toast(t('voiceReady'))};recorder.start();voiceUi(true,t('recording'))}catch(e){voiceUi(false);toast(e?.name==='NotAllowedError'?t('voiceDenied'):t('voiceError'))}}
async function startSpeech(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return startRecorder();try{try{await micPermission()}catch(e){return toast(e?.name==='NotAllowedError'?t('voiceDenied'):t('voiceError'))}speechBase=$('newText').value.trim();recognition=new R();recognition.lang=S.lang==='he'?'he-IL':'en-US';recognition.interimResults=true;recognition.continuous=false;recognition.maxAlternatives=1;recognition.onstart=()=>voiceUi(true,t('listening'));recognition.onresult=e=>{let final='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const s=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)final+=s;else interim+=s}$('newText').value=[speechBase,final||interim].filter(Boolean).join(' ').trim();if(final)speechBase=$('newText').value};recognition.onerror=e=>{voiceUi(false);if(e.error==='not-allowed'||e.error==='service-not-allowed')toast(t('voiceDenied'));else if(e.error==='no-speech')toast(t('voiceNoSpeech'));else if(e.error!=='aborted')toast(t('voiceError'))};recognition.onend=()=>voiceUi(false);recognition.start()}catch{voiceUi(false);startRecorder()}}
$('voice').onclick=()=>{if(recorder&&recorder.state==='recording')return recorder.stop();if(listening&&recognition){try{recognition.stop()}catch{}return}startSpeech()};
$('removeAudio').onclick=clearDraftAudio;
$('add').onclick=()=>{let text=$('newText').value.trim();if(!text&&!S.pendingAudioId)return toast(t('writeFirst'));if(!text)text=t('voiceNote');const v=S.pending||{};S.items.push({id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),text,type:$('newType').value,createdAt:new Date().toISOString(),archived:false,done:false,schedule:v.schedule||null,random:v.random||null,audioId:S.pendingAudioId||null,lastNotifiedAt:null});S.pendingAudioId=null;if(S.draftAudioUrl)URL.revokeObjectURL(S.draftAudioUrl);S.draftAudioUrl=null;$('audioDraft').classList.remove('show');$('draftAudio').removeAttribute('src');$('newText').value='';S.pending=null;save();updatePending();render();toast(t('added'))};
$('scheduleNew').onclick=()=>openSchedule();
$('randomOn').onchange=()=>$('randomWrap').classList.toggle('hidden',!$('randomOn').checked);
$('clearPending').onclick=()=>{S.pending=null;updatePending()};
$('scheduleForm').onsubmit=e=>{e.preventDefault();const v=scheduleValue();if(S.target){const i=S.items.find(x=>x.id===S.target);if(i){i.schedule=v.schedule;i.random=v.random;i.done=false;i.lastNotifiedAt=null}}else S.pending=v;save();render();updatePending();S.target=null;$('scheduleDlg').close();toast(t('updated'))};
$('clearSchedule').onclick=()=>{if(S.target){const i=S.items.find(x=>x.id===S.target);if(i){i.schedule=null;i.random=null;i.lastNotifiedAt=null}}else S.pending=null;save();render();updatePending();S.target=null;$('scheduleDlg').close()};
$('list').onclick=e=>{const c=e.target.closest('.card');if(!c)return;const i=S.items.find(x=>x.id===c.dataset.id);if(!i)return;if(e.target.closest('.edit')){S.edit=i.id;$('editText').value=i.text;$('editType').value=i.type||'thought';return $('editDlg').showModal()}if(e.target.closest('.schedule'))return openSchedule(i.id);if(e.target.closest('.complete')){advance(i);save();render();return}if(e.target.closest('.archive')){i.archived=!i.archived;save();render();return toast(i.archived?t('archivedToast'):t('restoredToast'))}if(e.target.closest('.delete')){S.del=i.id;return $('deleteDlg').showModal()}};
$('editForm').onsubmit=e=>{e.preventDefault();const i=S.items.find(x=>x.id===S.edit),v=$('editText').value.trim();if(i&&v){i.text=v;i.type=$('editType').value;save();render();toast(t('updated'))}S.edit=null;$('editDlg').close()};
$('editSchedule').onclick=()=>{const id=S.edit;$('editDlg').close();openSchedule(id)};
$('cancelDelete').onclick=()=>{S.del=null;$('deleteDlg').close()};
$('confirmDelete').onclick=()=>{const i=S.items.find(x=>x.id===S.del);if(i?.audioId)audioDelete(i.audioId);S.items=S.items.filter(x=>x.id!==S.del);S.del=null;save();render();$('deleteDlg').close();toast(t('deleted'))};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.filter=b.dataset.filter;render()});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('lang').onclick=()=>{S.lang=S.lang==='he'?'en':'he';localStorage.setItem('thoughts_lang',S.lang);lang()};
function checkReminders(){let changed=false;S.items.forEach(i=>{if(i.archived||i.done)return;if(!due(i))return;const last=i.lastNotifiedAt?new Date(i.lastNotifiedAt).getTime():0;if(Date.now()-last<15*60*1000)return;i.lastNotifiedAt=new Date().toISOString();if(i.random?.enabled&&i.random.nextAt&&new Date(i.random.nextAt)<=new Date())i.random.nextAt=nextRandom(i.random.frequency);if('Notification'in window&&Notification.permission==='granted')try{new Notification(S.lang==='he'?'תזכורת':'Reminder',{body:i.text})}catch{}changed=true});if(changed){save();render()}}
load();lang();checkReminders();setInterval(checkReminders,60000);
})();