(()=>{
const KEY='thoughts_assistant_v1';
const LEGACY=['thoughts_app_v2','thoughts','ideas','mindItems','thoughtsAppItems','thoughts_assistant','thoughtsAssistant','thoughts_app'];
const $=id=>document.getElementById(id);
const S={items:[],filter:'active',lang:localStorage.getItem('thoughts_lang')||'he',pending:null,target:null,edit:null,del:null,draftBlob:null,recorder:null,stream:null,legacy:[]};
const L={
he:{appName:'המחשבות שלי',eyebrow:'המקום שלך לזכור',headline:'מה עובר לך בראש?',subhead:'לכתוב, לדבר, לתזמן — ולחזור לזה בדיוק בזמן.',placeholder:'כתוב משהו שלא תרצה לשכוח...',typeThought:'מחשבה / משימה',typeEvent:'אירוע',typeFriend:'חבר / אדם',schedule:'תזמון',add:'הוסף',activeStat:'פעילים',scheduledStat:'מתוזמנים',dueStat:'עכשיו',yourThoughts:'המחשבות שלך',yourThoughtsSub:'מה שחשוב נשאר קרוב.',active:'פעילים',archived:'ארכיון',all:'הכול',emptyTitle:'הכול מסודר',empty:'הפריט הבא שלך מתחיל למעלה.',local:'המחשבות נשמרות במכשיר הזה.',scheduleTitle:'מתי להזכיר לך?',date:'תאריך',time:'שעה',repeat:'חזרה',none:'ללא חזרה',daily:'כל יום',threeDays:'כל 3 ימים',weekly:'כל שבוע',biweekly:'כל שבועיים',monthly:'כל חודש',bimonthly:'כל חודשיים',random:'להפתיע אותי',randomHelp:'להחזיר את הפריט בזמן אקראי לפי התדירות.',frequency:'תדירות',clear:'ללא תזמון',save:'שמירה',itemType:'סוג פריט',content:'תוכן',editTitle:'עריכת פריט',changeSchedule:'שינוי תזמון',saveChanges:'שמירה',deleteTitle:'למחוק?',deleteHelp:'המחיקה סופית. אפשר להעביר לארכיון במקום.',cancel:'ביטול',delete:'מחיקה',edit:'עריכה',archive:'ארכיון',restore:'החזרה',done:'בוצע',nextOccurrence:'הבא',scheduled:'מתוזמן',repeats:'חוזר',due:'הגיע הזמן',randomChip:'אקראי',voiceNote:'הקלטה קולית',added:'נוסף',updated:'עודכן',deleted:'נמחק',archivedToast:'הועבר לארכיון',restoredToast:'הוחזר',next:'נקבע המועד הבא',writeFirst:'כתוב או הקלט משהו קודם',listening:'מקשיב… דבר עכשיו',recording:'מקליט… לחץ שוב לעצירה',voiceReady:'ההקלטה מוכנה',voiceDenied:'אין הרשאה למיקרופון',voiceNoSpeech:'לא זוהה דיבור. אפשר לנסות שוב.',voiceError:'ההקלטה לא הצליחה',migrationTitle:'מצאתי מחשבות מהאפליקציה הישנה',migrationText:'אפשר למזג אותן לכאן בלי למחוק שום דבר שקיים באתר.',migrate:'ייבוא',import:'ייבוא מהאפליקציה הישנה',export:'גיבוי המחשבות',importTitle:'ייבוא מחשבות',importHelp:'הדבק כאן JSON שיוצא מהאפליקציה הישנה. פריטים קיימים לא יימחקו.',importNow:'ייבוא עכשיו',imported:'המחשבות יובאו בהצלחה',nothingToImport:'לא נמצאו מחשבות חדשות לייבוא',backupReady:'קובץ הגיבוי מוכן'},
en:{appName:'My Thoughts',eyebrow:'Your place to remember',headline:"What's on your mind?",subhead:'Write it, say it, schedule it — and return to it at the right time.',placeholder:"Write something you don't want to forget...",typeThought:'Thought / task',typeEvent:'Event',typeFriend:'Friend / person',schedule:'Schedule',add:'Add',activeStat:'Active',scheduledStat:'Scheduled',dueStat:'Now',yourThoughts:'Your thoughts',yourThoughtsSub:'What matters stays close.',active:'Active',archived:'Archive',all:'All',emptyTitle:'All clear',empty:'Your next item starts above.',local:'Thoughts are stored on this device.',scheduleTitle:'When should I remind you?',date:'Date',time:'Time',repeat:'Repeat',none:'No repeat',daily:'Daily',threeDays:'Every 3 days',weekly:'Weekly',biweekly:'Every 2 weeks',monthly:'Monthly',bimonthly:'Every 2 months',random:'Surprise me',randomHelp:'Bring this item back randomly at the selected frequency.',frequency:'Frequency',clear:'No schedule',save:'Save',itemType:'Item type',content:'Content',editTitle:'Edit item',changeSchedule:'Change schedule',saveChanges:'Save',deleteTitle:'Delete?',deleteHelp:'Deletion is permanent. You can archive it instead.',cancel:'Cancel',delete:'Delete',edit:'Edit',archive:'Archive',restore:'Restore',done:'Done',nextOccurrence:'Next',scheduled:'Scheduled',repeats:'Repeats',due:'Due now',randomChip:'Random',voiceNote:'Voice note',added:'Added',updated:'Updated',deleted:'Deleted',archivedToast:'Archived',restoredToast:'Restored',next:'Next occurrence scheduled',writeFirst:'Write or record something first',listening:'Listening… speak now',recording:'Recording… tap again to stop',voiceReady:'Recording ready',voiceDenied:'Microphone permission denied',voiceNoSpeech:'No speech detected. Try again.',voiceError:'Voice capture failed',migrationTitle:'I found thoughts from the old app',migrationText:'You can merge them here without deleting anything already on the website.',migrate:'Import',import:'Import from old app',export:'Back up thoughts',importTitle:'Import thoughts',importHelp:'Paste JSON exported from the old app. Existing items will not be deleted.',importNow:'Import now',imported:'Thoughts imported',nothingToImport:'No new thoughts found',backupReady:'Backup ready'}};
const t=k=>L[S.lang][k]||k;
const save=()=>localStorage.setItem(KEY,JSON.stringify(S.items));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=x=>{const e=$('toast');e.textContent=x;e.classList.add('show');clearTimeout(toast.h);toast.h=setTimeout(()=>e.classList.remove('show'),1800)};
function normalize(x,n=0){const schedule=x.schedule||((x.date&&x.time)?{date:x.date,time:x.time,repeat:x.repeat||'none'}:null);return{id:String(x.id||x.uuid||`${Date.now()}_${n}_${Math.random().toString(36).slice(2,7)}`),text:String(x.text||x.title||x.content||x.note||''),type:['thought','event','friend'].includes(x.type)?x.type:'thought',createdAt:x.createdAt||x.created||x.timestamp||new Date().toISOString(),archived:!!x.archived,done:!!x.done,schedule,random:x.random||null,audioId:x.audioId||null,lastNotifiedAt:x.lastNotifiedAt||null}}
function fingerprint(i){return`${(i.text||'').trim().toLowerCase()}|${i.createdAt||''}|${i.type||'thought'}`}
function extractArray(raw){try{const v=typeof raw==='string'?JSON.parse(raw):raw;if(Array.isArray(v))return v;if(v&&Array.isArray(v.items))return v.items;if(v&&Array.isArray(v.thoughts))return v.thoughts;if(v&&Array.isArray(v.data))return v.data}catch{}return[]}
function discoverLegacy(){const found=[];const seen=new Set();for(let n=0;n<localStorage.length;n++){const k=localStorage.key(n);if(!k||k===KEY||k==='thoughts_lang')continue;let arr=[];try{arr=extractArray(localStorage.getItem(k))}catch{}if(!arr.length)continue;for(const x of arr){const i=normalize(x,found.length);if(!i.text&&!i.audioId)continue;const f=fingerprint(i);if(!seen.has(f)){seen.add(f);found.push(i)}}}return found}
function load(){try{S.items=extractArray(localStorage.getItem(KEY)).map(normalize).filter(i=>i.text||i.audioId)}catch{S.items=[]}S.legacy=discoverLegacy().filter(i=>!new Set(S.items.map(fingerprint)).has(fingerprint(i)));$('migrationBox').classList.toggle('hidden',!S.legacy.length)}
function mergeItems(items){const have=new Set(S.items.map(fingerprint));let count=0;for(const x of items.map(normalize)){if(!x.text&&!x.audioId)continue;const f=fingerprint(x);if(have.has(f))continue;have.add(f);S.items.push(x);count++}if(count){save();render();S.legacy=discoverLegacy().filter(i=>!new Set(S.items.map(fingerprint)).has(fingerprint(i)));$('migrationBox').classList.toggle('hidden',!S.legacy.length);toast(t('imported'))}else toast(t('nothingToImport'));return count}
function iso(s){if(!s?.date||!s?.time)return null;const d=new Date(`${s.date}T${s.time}:00`);return isNaN(d)?null:d.toISOString()}
function fmt(x){if(!x)return'';try{return new Intl.DateTimeFormat(S.lang==='he'?'he-IL':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x))}catch{return''}}
function due(i){const a=iso(i.schedule),b=i.random?.enabled?i.random.nextAt:null;return!!((a&&new Date(a)<=new Date())||(b&&new Date(b)<=new Date()))}
function addMonths(d,n){const day=d.getDate();d=new Date(d);d.setDate(1);d.setMonth(d.getMonth()+n);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d}
function nextDate(d,r){d=new Date(d);if(r==='daily')d.setDate(d.getDate()+1);else if(r==='3days')d.setDate(d.getDate()+3);else if(r==='weekly')d.setDate(d.getDate()+7);else if(r==='biweekly')d.setDate(d.getDate()+14);else if(r==='monthly')d=addMonths(d,1);else if(r==='bimonthly')d=addMonths(d,2);return d}
function rndMs(v){return({daily:86400000,'3days':259200000,weekly:604800000,biweekly:1209600000})[v]||86400000}
function nextRandom(v){const span=rndMs(v);return new Date(Date.now()+7200000+Math.random()*Math.max(1,span-7200000)).toISOString()}
function repeatText(v){return v==='3days'?t('threeDays'):t(v||'none')}
function typeText(v){return t(v==='event'?'typeEvent':v==='friend'?'typeFriend':'typeThought')}
function render(){const active=S.items.filter(i=>!i.archived);$('activeCount').textContent=active.length;$('scheduledCount').textContent=active.filter(i=>i.schedule||i.random?.enabled).length;$('dueCount').textContent=active.filter(due).length;const arr=S.items.filter(i=>S.filter==='all'||(S.filter==='active'?!i.archived:i.archived)).sort((a,b)=>(due(a)?0:1)-(due(b)?0:1)||new Date(b.createdAt)-new Date(a.createdAt));$('list').innerHTML='';$('empty').classList.toggle('hidden',!!arr.length);for(const i of arr){const card=document.createElement('article');const si=iso(i.schedule);const chips=[`<span class="chip ${i.type==='event'?'event':i.type==='friend'?'friend':'type'}">${esc(typeText(i.type))}</span>`];if(due(i))chips.push(`<span class="chip due">${esc(t('due'))}</span>`);if(si)chips.push(`<span class="chip">${esc(fmt(si))}</span>`);if(i.schedule?.repeat&&i.schedule.repeat!=='none')chips.push(`<span class="chip repeat">${esc(t('repeats'))}: ${esc(repeatText(i.schedule.repeat))}</span>`);if(i.random?.enabled)chips.push(`<span class="chip repeat">${esc(t('randomChip'))}: ${esc(repeatText(i.random.frequency))}</span>`);if(i.done)chips.push(`<span class="chip done">${esc(t('done'))}</span>`);const recurring=!!(i.schedule?.repeat&&i.schedule.repeat!=='none');card.className=`card${due(i)?' due':si?' scheduled':''}`;card.dataset.id=i.id;card.innerHTML=`<div class="card-top"><span class="status-mark"></span><div style="flex:1"><div class="thought">${esc(i.text||t('voiceNote'))}</div><div class="chips">${chips.join('')}</div><div class="audio-card ${i.audioId?'':'hidden'}" data-audio="${esc(i.audioId||'')}"></div><div class="meta">${esc(fmt(i.createdAt))}</div></div></div><div class="card-actions"><button class="small edit">${esc(t('edit'))}</button><button class="small schedule">${esc(t('schedule'))}</button><button class="small complete">${esc(recurring?t('nextOccurrence'):t('done'))}</button><button class="small archive">${esc(i.archived?t('restore'):t('archive'))}</button><button class="small delete">${esc(t('delete'))}</button></div>`;$('list').appendChild(card)}hydrateAudio()}
function applyLang(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==='he'?'rtl':'ltr';document.querySelectorAll('[data-t]').forEach(e=>e.textContent=t(e.dataset.t));document.querySelectorAll('[data-ph]').forEach(e=>e.placeholder=t(e.dataset.ph));$('lang').textContent=S.lang==='he'?'EN':'עברית';render();updatePending()}
function updatePending(){const e=$('pending');if(!S.pending?.schedule&&!S.pending?.random){e.classList.remove('show');return}const p=[];if(S.pending.schedule)p.push(fmt(iso(S.pending.schedule)));if(S.pending.schedule?.repeat&&S.pending.schedule.repeat!=='none')p.push(`${t('repeats')} · ${repeatText(S.pending.schedule.repeat)}`);if(S.pending.random?.enabled)p.push(`${t('randomChip')} · ${repeatText(S.pending.random.frequency)}`);$('pendingText').textContent=p.join(' · ');e.classList.add('show')}
function openSchedule(id=null){S.target=id;const item=id?S.items.find(x=>x.id===id):S.pending||{};const s=item.schedule||{},r=item.random||{},now=new Date(),p=n=>String(n).padStart(2,'0');$('date').value=s.date||`${now.getFullYear()}-${p(now.getMonth()+1)}-${p(now.getDate())}`;$('time').value=s.time||`${p(Math.min(23,now.getHours()+1))}:00`;$('repeat').value=s.repeat||'none';$('randomOn').checked=!!r.enabled;$('frequency').value=r.frequency||'daily';$('randomWrap').classList.toggle('hidden',!r.enabled);$('scheduleDlg').showModal()}
function scheduleValue(){return{schedule:$('date').value&&$('time').value?{date:$('date').value,time:$('time').value,repeat:$('repeat').value}:null,random:$('randomOn').checked?{enabled:true,frequency:$('frequency').value,nextAt:nextRandom($('frequency').value)}:null}}
function advance(i){const r=i.schedule?.repeat,si=iso(i.schedule);if(si&&r&&r!=='none'){let n=nextDate(new Date(si),r);while(n<=new Date())n=nextDate(n,r);const p=x=>String(x).padStart(2,'0');i.schedule.date=`${n.getFullYear()}-${p(n.getMonth()+1)}-${p(n.getDate())}`;i.schedule.time=`${p(n.getHours())}:${p(n.getMinutes())}`;i.done=false;if(i.random?.enabled)i.random.nextAt=nextRandom(i.random.frequency);toast(t('next'))}else i.done=true;save();render()}
const DB='thoughts_voice_db';function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('audio'))q.result.createObjectStore('audio')};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}async function dbPut(id,blob){const d=await db();await new Promise((res,rej)=>{const tx=d.transaction('audio','readwrite');tx.objectStore('audio').put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});d.close()}async function dbGet(id){const d=await db();const v=await new Promise((res,rej)=>{const q=d.transaction('audio').objectStore('audio').get(id);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)});d.close();return v}async function hydrateAudio(){for(const e of document.querySelectorAll('[data-audio]:not(.hidden)')){if(e.dataset.ready)continue;e.dataset.ready='1';try{const b=await dbGet(e.dataset.audio);if(b){const a=document.createElement('audio');a.controls=true;a.src=URL.createObjectURL(b);e.appendChild(a)}}catch{}}}
async function startVoice(){if(S.recorder){stopVoice();return}const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){try{await navigator.mediaDevices.getUserMedia({audio:true}).then(s=>s.getTracks().forEach(t=>t.stop()));const r=new SR();r.lang=S.lang==='he'?'he-IL':'en-US';r.interimResults=false;r.maxAlternatives=1;$('voice').classList.add('listening');$('voiceState').classList.add('show');$('voiceLabel').textContent=t('listening');r.onresult=e=>{$('newText').value=($('newText').value+' '+e.results[0][0].transcript).trim()};r.onerror=e=>{if(e.error==='not-allowed')toast(t('voiceDenied'));else if(e.error!=='aborted')toast(t('voiceNoSpeech'))};r.onend=()=>{$('voice').classList.remove('listening');$('voiceState').classList.remove('show')};r.start();return}catch{}}try{S.stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks=[];S.recorder=new MediaRecorder(S.stream);S.recorder.ondataavailable=e=>chunks.push(e.data);S.recorder.onstop=()=>{S.draftBlob=new Blob(chunks,{type:S.recorder?.mimeType||'audio/webm'});$('draftAudio').src=URL.createObjectURL(S.draftBlob);$('audioDraft').classList.add('show');$('voiceState').classList.remove('show');$('voice').classList.remove('listening');S.stream?.getTracks().forEach(t=>t.stop());S.recorder=null};S.recorder.start();$('voice').classList.add('listening');$('voiceState').classList.add('show');$('voiceLabel').textContent=t('recording')}catch{toast(t('voiceDenied'))}}
function stopVoice(){try{S.recorder?.stop()}catch{}}
async function addItem(){const text=$('newText').value.trim();if(!text&&!S.draftBlob){toast(t('writeFirst'));return}let audioId=null;if(S.draftBlob){audioId=`audio_${Date.now()}`;try{await dbPut(audioId,S.draftBlob)}catch{audioId=null}}S.items.push(normalize({text,type:$('newType').value,createdAt:new Date().toISOString(),schedule:S.pending?.schedule||null,random:S.pending?.random||null,audioId}));save();$('newText').value='';S.pending=null;S.draftBlob=null;$('audioDraft').classList.remove('show');$('draftAudio').removeAttribute('src');updatePending();render();toast(t('added'))}
function exportData(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),items:S.items},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`thoughts-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(t('backupReady'))}
$('lang').onclick=()=>{S.lang=S.lang==='he'?'en':'he';localStorage.setItem('thoughts_lang',S.lang);applyLang()};$('add').onclick=addItem;$('voice').onclick=startVoice;$('removeAudio').onclick=()=>{S.draftBlob=null;$('audioDraft').classList.remove('show');$('draftAudio').removeAttribute('src')};$('scheduleNew').onclick=()=>openSchedule();$('clearPending').onclick=()=>{S.pending=null;updatePending()};$('randomOn').onchange=e=>$('randomWrap').classList.toggle('hidden',!e.target.checked);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('clearSchedule').onclick=()=>{$('scheduleDlg').close();if(S.target){const i=S.items.find(x=>x.id===S.target);if(i){i.schedule=null;i.random=null;save();render()}}else{S.pending=null;updatePending()}};$('scheduleForm').onsubmit=e=>{e.preventDefault();const v=scheduleValue();$('scheduleDlg').close();if(S.target){const i=S.items.find(x=>x.id===S.target);if(i){i.schedule=v.schedule;i.random=v.random;i.done=false;save();render()}}else{S.pending=v;updatePending()}};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.filter=b.dataset.filter;render()});$('list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const card=e.target.closest('.card'),i=S.items.find(x=>x.id===card?.dataset.id);if(!i)return;if(b.classList.contains('edit')){S.edit=i.id;$('editText').value=i.text;$('editType').value=i.type;$('editDlg').showModal()}else if(b.classList.contains('schedule'))openSchedule(i.id);else if(b.classList.contains('complete'))advance(i);else if(b.classList.contains('archive')){i.archived=!i.archived;save();render();toast(i.archived?t('archivedToast'):t('restoredToast'))}else if(b.classList.contains('delete')){S.del=i.id;$('deleteDlg').showModal()}};$('editForm').onsubmit=e=>{e.preventDefault();const i=S.items.find(x=>x.id===S.edit);if(i){i.text=$('editText').value.trim();i.type=$('editType').value;save();render();toast(t('updated'))}$('editDlg').close()};$('editSchedule').onclick=()=>{$('editDlg').close();openSchedule(S.edit)};$('cancelDelete').onclick=()=> $('deleteDlg').close();$('confirmDelete').onclick=()=>{S.items=S.items.filter(i=>i.id!==S.del);save();render();$('deleteDlg').close();toast(t('deleted'))};$('migrateBtn').onclick=()=>mergeItems(S.legacy);$('importBtn').onclick=()=>{$('importText').value='';$('importDlg').showModal()};$('importForm').onsubmit=e=>{e.preventDefault();mergeItems(extractArray($('importText').value));$('importDlg').close()};$('exportBtn').onclick=exportData;
load();applyLang();setInterval(render,60000);
})();